spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pickupdb
    username: root
    password: root
  sql:
    init:
      mode: always

  application:
    name: pickup-service

server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
